apiVersion: project.jenkins-x.io/v1alpha1
kind: Quickstarts
spec:
  defaultOwner: myorg

  # custom quickstarts
  quickstarts:
  - name: cheese
    language: Java
    downloadZipURL: https://github.com/Activiti/activiti-cloud-application/archive/refs/heads/develop.zip


  # shared quickstarts
  imports:
  - file: versionStream/quickstarts.yaml
    includes:
    - ".*"
    excludes: []
