apiVersion: v1
data:
  config.yaml: |
    branch-protection:
      protect-tested-repos: true
    github:
      LinkURL: null
    in_repo_config:
      enabled:
        jenkins-serverless-gke/gke-cluster-secret: true
        jenkins-serverless-gke/nodeapp: true
        jenkins-serverless-gke/nodeapp-night: true
        jenkins-serverless-gke/nodeapp3: true
        jenkins-serverless-gke/ttc-dashboard-ui: true
        jenkins-serverless-gke/twitter-angular-dashboard: true
        jenkins-serverless-gke/twitter-ui: true
        serverless-bot-726/activiti-gke: true
        serverless-bot-726/nodenewapp: true
        serverless-bot-726/twitter-dashboard-ui: true
    plank: {}
    pod_namespace: jx
    prowjob_namespace: jx
    push_gateway:
      serve_metrics: true
    tide:
      context_options:
        from-branch-protection: true
        required-if-present-contexts: null
        skip-unknown-contexts: false
      merge_method:
        jenkins-serverless-gke/gke-cluster-secret: merge
        jenkins-serverless-gke/nodeapp: merge
        jenkins-serverless-gke/nodeapp-night: merge
        jenkins-serverless-gke/nodeapp3: merge
        jenkins-serverless-gke/ttc-dashboard-ui: merge
        jenkins-serverless-gke/twitter-angular-dashboard: merge
        jenkins-serverless-gke/twitter-ui: merge
        serverless-bot-726/activiti-gke: merge
        serverless-bot-726/nodenewapp: merge
        serverless-bot-726/twitter-dashboard-ui: merge
      queries:
      - labels:
        - approved
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - jenkins-serverless-gke/gke-cluster-secret
        - jenkins-serverless-gke/nodeapp-night
        - jenkins-serverless-gke/nodeapp
        - jenkins-serverless-gke/nodeapp3
        - jenkins-serverless-gke/ttc-dashboard-ui
        - jenkins-serverless-gke/twitter-angular-dashboard
        - jenkins-serverless-gke/twitter-ui
        - serverless-bot-726/activiti-gke
        - serverless-bot-726/nodenewapp
        - serverless-bot-726/twitter-dashboard-ui
      - labels:
        - updatebot
        missingLabels:
        - do-not-merge
        - do-not-merge/hold
        - do-not-merge/work-in-progress
        - needs-ok-to-test
        - needs-rebase
        repos:
        - jenkins-serverless-gke/gke-cluster-secret
        - jenkins-serverless-gke/nodeapp-night
        - jenkins-serverless-gke/nodeapp
        - jenkins-serverless-gke/nodeapp3
        - jenkins-serverless-gke/ttc-dashboard-ui
        - jenkins-serverless-gke/twitter-angular-dashboard
        - jenkins-serverless-gke/twitter-ui
        - serverless-bot-726/activiti-gke
        - serverless-bot-726/nodenewapp
        - serverless-bot-726/twitter-dashboard-ui
      target_url: http://lighthouse-jx.34.132.47.65.nip.io/merge/status
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: config
  namespace: jx
  labels:
    gitops.jenkins-x.io/pipeline: 'namespaces'
