apiVersion: gitops.jenkins-x.io/v1alpha1
kind: SourceConfig
metadata:
  creationTimestamp: null
spec:
  groups:
  - owner: jenkins-serverless-gke
    provider: https://github.com
    providerKind: github
    repositories:
    - name: gcloud-activiti
    - name: gcloud-again
    - name: nodeapp
    - name: nodeapp-night
    - name: nodeapp3
    - name: theNodeApp
    - name: ttc-dashboard-ui
    - name: twitter-angular-dashboard
    - name: twitter-ui
    - name: yoYoYo
    scheduler: in-repo
  - owner: serverless-bot-726
    provider: https://github.com
    providerKind: github
    repositories:
    - name: activiti-cloud-gke
    - name: activiti-gke
    - name: gke-cloud
    - name: nodenewapp
    - name: twitter-dashboard-ui
    scheduler: in-repo
  slack:
    channel: '#jenkins-x-pipelines'
    kind: failureOrNextSuccess
    pipeline: release
